name: capstone_home_doctor
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  rxdart: ^0.24.1
  firebase_analytics: ^6.3.0
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  firebase_auth: 
  flutter_local_notifications: ^3.0.2
  cloud_firestore: ^0.14.4
  uuid: ^2.2.2
  cached_network_image: ^2.4.1
  intl: ^0.16.1
  sqflite: ^1.3.2+2
  geolocator: ^6.1.13
  signalr_core: ^1.0.8
  barcode_scan: ^2.0.1
  url_launcher: ^5.7.10
  flutter_blue: ^0.7.3
  image_picker: ^0.6.7+22
  path_provider: ^1.6.27
  android_alarm_manager: ^0.4.5+20
  flutter_rounded_date_picker: 1.0.5
  workmanager: ^0.2.3
  cron: ^0.2.4
  fl_chart: ^0.12.3
  flutter_echarts: ^1.5.0
  custom_radio_grouped_button: ^1.0.6+1
  jwt_decoder: ^1.0.4
  string_similarity: ^1.1.0

  agora_rtc_engine: ^3.1.6
  permission_handler: ^5.0.1+1
  autocomplete_textfield: ^1.7.3
  table_calendar: ^2.3.3
  expandable_group: ^0.0.7
  photo_view: ^0.10.0
  connectivity: ^2.0.2
  percent_indicator: 2.1.9+1
  tesseract_ocr: ^0.3.1
  sentry_flutter: ^4.0.6
  flutter_cupertino_localizations: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/tessdata/
    - assets/images/avatar-default.jpg
    - assets/images/logo-home-doctor.png
    - assets/images/ic-pop.png
    - assets/images/ic-dashboard.png
    - assets/images/ic-dashboard-selected.png
    - assets/images/ic-health.png
    - assets/images/ic-health-selected.png
    - assets/images/ic-msg.png
    - assets/images/ic-msg-selected.png
    - assets/images/ic-noti.png
    - assets/images/ic-noti-selected.png
    - assets/images/ic-detail.png
    - assets/images/ic-new-msg.png
    - assets/images/ic-navigator.png
    - assets/images/ic-scan-qr.png
    - assets/images/ic-back-home.png
    - assets/images/ic-connect-p.png
    - assets/images/ic-heart-rate.png
    - assets/images/ic-blood-pressure.png
    - assets/images/ic-spo2.png
    - assets/images/ic-oxy.png
    - assets/images/ic-tempurature.png
    - assets/images/img-device.png
    - assets/images/img-bluetooth.png
    - assets/images/ic-contract.png
    - assets/images/img-amazfit.png
    - assets/images/img-mi-band.png
    - assets/images/img-galaxy-fit-e.png
    - assets/images/ic-choose-date.png
    - assets/images/loading.gif
    - assets/images/ic-done.png
    - assets/images/ic-failed.png
    - assets/images/ic-dropdown.png
    - assets/images/ic-id.png
    - assets/images/ic-contract-empty.png
    - assets/images/ic-dot.png
    - assets/images/ic-close.png
    - assets/images/ic-find.png
    - assets/images/ic-dot-unselect.png
    - assets/images/ic-medicine.png
    - assets/images/ic-calendar.png
    - assets/images/ic-more.png
    - assets/images/ic-remove.png
    - assets/images/ic-health-record.png
    - assets/images/ic-male.png
    - assets/images/ic-female.png
    - assets/images/img-unknown-device.png
    - assets/images/ic-medical-instruction.png
    - assets/images/ic-map.png
    - assets/images/ic-note.png
    - assets/images/ic-add-more-mi.png
    - assets/images/ic-add-disease.png
    - assets/images/ic-down.png
    - assets/images/ic-contract-list.png
    - assets/images/ic-information-list.png
    - assets/images/ic-device-list.png
    - assets/images/ic-c-pending.png
    - assets/images/ic-c-approved.png
    - assets/images/ic-c-active.png
    - assets/images/ic-c-finished.png
    - assets/images/ic-c-pending-u.png
    - assets/images/ic-c-approved-u.png
    - assets/images/ic-c-active-u.png
    - assets/images/ic-c-finished-u.png
    - assets/images/ic-people.png
    - assets/images/ic-money.png
    - assets/images/ic-deny.png
    - assets/images/ic-checked.png
    - assets/images/ic-mi-band.png
    - assets/images/ic-unknown-device.png
    - assets/images/ic-reload.png
    - assets/images/ic-heart-dangerous.gif
    - assets/images/ic-heart-u.png
    - assets/images/ic-spo2-u.png
    - assets/images/ic-temp-u.png
    - assets/images/ic-pressure-u.png
    - assets/images/ic-filter.png
    - assets/images/ic-health-record-u.png
    - assets/images/ic-create.png
    - assets/images/ic-acti.png
    - assets/images/ic-acti-u.png
    - assets/images/ic-next.png
    - assets/images/ic-prev.png
    - assets/images/ic-c-cancel.png
    - assets/images/ic-filter-black.png
    - assets/images/bg-home.png
    - assets/images/ic-bluetooth.png
    - assets/images/ic-create-hr.png
    - assets/images/ic-c-signed.png
    - assets/images/ic-c-signed-u.png
    - assets/images/ic-all-vital.png


  
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # assets:
  #   - assets/music/Sound_Horizon.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
        - asset: assets/fonts/SF-Pro-Italic.ttf
          style: italic
    
    - family: SFProRounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf

    - family: NewYork
      fonts:
        - asset: assets/fonts/NewYork.ttf
        - asset: assets/fonts/NewYorkItalic.ttf
          style: italic
        
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
